### ISSUE TITLE
Speed of sound in configuration file

### ISSUE THREAD

**Issue by BSchilperoort** [tomchor/pymicra#3]
Our WMPro sonic outputs the measured speed of sound, not the sonic temperature. Could this be added to the configuration input?

**Comment by tomchor** [comment]
Do you mean put it in the `.config` files and read it automatically? If so, yes. You can really name the data anything you want in order to read it. The thing is that if the data isn't properly named the functions used afterwards (like `pm.micro.preProcess` will not work).

Below is a minimum example using the example data in Pymicra. Note that the 10th column isn't really the sound speed, I put it there just as an illustration.

Contents of `lake.config`:

```
description='datalogger configuration file for a lake. Located at examples/lake.config'

variables={
0:'%Y-%m-%d',
1:'%H:%M:%S.%f',
2:'u',
3:'v',
4:'w',
5:'theta_v',
6:'mrho_h2o',
7:'mrho_co2',
8:'p',
9:'theta',
10:'sound_speed'}

units={
'u':'m/s',
'v':'m/s',
'w':'m/s',
'theta_v':'celsius',
'mrho_co2':'mmol/m**3',
'mrho_h2o':'mmol/m**3',
'p':'kPa',
'theta':'celsius',
'sound_speed':'m/s'
}

columns_separator=','
frequency=20
header_lines=None

filename_format='%Y%m%d-%H%M.csv'
date_cols = [0, 1]
```

Main program:

```
import pymicra as pm
fileconf = pm.fileConfig('lake.config')
fin='ex_data/20131108-1000.csv'

data, units = pm.timeSeries(fin, fileconf, parse_dates=True)
print(data.columns)
```
prints out `Index(['u', 'v', 'w', 'theta_v', 'mrho_h2o', 'mrho_co2', 'p', 'theta', 'sound_speed'], dtype='object')
`

Please let me know if this answers your question.

P.S.: At the moment, there isn't any functionality to take advantage of the sound speed, so you will have to write your own. If you do, feel free to contribute!

**Comment by BSchilperoort** [comment]
That should work for the input yes, but converting the speed of sound to sonic temperature would be nice to have implemented. 

I guess the conversion has to be added to the preprocessing step? (And include the conversion to actual & virtual temperature there if the required data is available)

**Comment by tomchor** [comment]
Unfortunately, like I said, there isn't any functionality for sound speed yet. So there isn't a conversion to sonic temperature yet. 

This step ideally would be added to the preProcessing step, yes. If you want the easy way you can just create a function that does it separately and put it before the `preProcess()` call. If you do that, it would be great if you could share you code so it can be implemented (I can implement it or you can). Any thoughts on that?

**Comment by BSchilperoort** [comment]
The conversion is quite basic, based on Schotanus et al. 1983:
`T_s = 1/403 * c**2`, with sonic temperature _T_s_ [K] and speed of sound _c_ [m/s].
(Although the 'constant' is now [said to be 402](http://www.apptech.com/wp-content/uploads/2016/04/sonic-thermometry.pdf) due to the increased CO2 concentration in the air)

The next step can then be calculating the air temperature, if humidity data is available:
`T = T_s / (1 + 0.51*q)` Where _T_ is the air temperature [K], and _q_ is the specific humidity [kg/kg]

**Comment by tomchor** [comment]
Marked this as an enhancement. For now I won't have much time to do enhancements, so let me know if you wanna code this :)

**Comment by BSchilperoort** [comment]
I already coded most of it yesterday, micro.preProcessing how can work even if you don't have h2o data, and will convert c to theta_s. I've made a pull request.

**Comment by tomchor** [comment]
Thanks!
